In [21]:
import numpy as np
import pandas as pd

In [22]:
df=pd.read_csv('customer.csv')

In [23]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [25]:
df = df.iloc[:,2:]

In [26]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [27]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [28]:
x_train

     review education
43     Poor        PG
18     Good    School
19     Poor        PG
48     Good        UG
12     Poor    School
10     Good        UG
32  Average        UG
30  Average        UG
3      Good        PG
5   Average    School
14     Poor        PG
23     Good    School
37  Average        PG
20  Average    School
24  Average        PG
33     Good        PG
41     Good        PG
21  Average        PG
27     Poor        PG
8   Average        UG
4   Average        UG
40     Good    School
17     Poor        UG
2      Good        PG
44  Average        UG
16     Poor        UG
31     Poor    School
7      Poor    School
38     Good    School
15     Poor        UG
45     Poor        PG
6      Good    School
36     Good        UG
42     Good        PG
26     Poor        PG
29  Average        UG
34  Average    School
39     Poor        PG
1      Poor        UG
46     Poor        PG

In [29]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [30]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [34]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [35]:
x_train

array([[0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 2.]])

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le=LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [38]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [39]:
y_train

array([0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0])